### ISSUE TITLE
`Ipv4Net` `FromStr` allows host bits to be set in CIDR

### ISSUE THREAD

**Issue by nu11ptr** [krisprice/ipnet#33]
This should return an error since a /24 would require a zero 4th octet, but it accepts it. Worse, it doesn't seem to transform it, but keeps all the bits set.

```rust
use std::str::FromStr;
use ipnet::Ipv4Net;

fn main() {
    let net = Ipv4Net::from_str("1.1.1.1/24");
    assert!(net.is_ok());
    println!("{}", net.unwrap());
}
```

NOTE: I just found the `trunc` function so now I'm starting to think this is per design. For the record, I think this is broken behavior as these are in no way valid subnets. My preference, and I believe correct behavior, would be to reject these outright. However, if this is kept, it would be nice if `trunc` could at least run by default so Serde, etc. can properly transform the data. Since there is no way to call `trunc` in the deserialization path that I'm aware of, it has to be a per call site type thing which is error prone.

Thanks for looking at this.

**Comment by nu11ptr** [comment]
Just hit another downside of not rejecting bad subnets or at least auto running `trunc`: there will be duplicates when putting them in a set as `1.1.1.0/24` and `1.1.1.1/24` will not be considered equal.

**Comment by krisprice** [comment]
Thanks @nu11ptr. Yep it was designed that way. Rejecting it would be preferable to silently transforming it. Possibly that's what I should've done, but the structure can show up in all kinds of places that aren't purely IP routes/prefixes, so I wanted to leave it flexible. Wonder if it's worth surveying users to see what they prefer and if changing this behaviour in a future release would affect them? Could leave this to a v3 update

**Comment by nu11ptr** [comment]
Thanks for the reply and consideration. 

I look at this way - your crate is either the only one, or certainly the most popular, to provide this. Thus, anyone who wants to implement network/subnet-like functionality is either using your crate or reinventing. I would expect almost all those who need to do this are going to want the behavior I describe (and I agree rejecting is better). It would be easy to leave a backdoor API if someone really needs the old behavior (`fn from_host_bits_str()`), but it should be easy to do the right thing (`FromStr`) and out of the way for the exception case.

**Comment by ens-scmeeu** [comment]
It's me again (this is my work github account, the other was my personal). As expected, this caused us bugs in our software (we are still using 2.10 I see). We use this type hundreds of times in our large code base and I'm guessing I just missed a `trunc()` somewhere. Perhaps I can make a suggestion?

I am not clear what use cases you are trying to preserve by accepting invalid subnets, but might I suggest:

a) enumerating what use cases the types are for (and I did think of one additional one for starters)
b) Splitting any use cases that are not valid subnets into a new type (the use case I thought of: IP address + mask, I would create an `Ipv4AddrAndMask` type, and enforce only IPs that are valid within that subnet)
c) Changing `Ipv4Net` to only be valid subnets and remove `trunc()` (or make it no-op if not bumping major ver)
d) Release as a v3 with this change (probably best to indicate a change in behavior)

P.S. - In hindsight, I should have wrapped this in my own newtype struct, forced a `trunc` on creation, and returned my own error if truncated value did not match input value. At this point, that is now a bit painful, but I still might do it you don't agree to this (and I might not be able to wait even if you do).

**Comment by ens-scmeeu** [comment]
For example, this is what I get from my example under Python. Hopefully we can agree that Rust tries to be more strict in its type validation than Python, so feature parity would not exactly be surprising or demanding I don't think.

```python
>>> ipaddress.IPv4Network("1.1.1.1/24")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/ipaddress.py", line 1530, in __init__
    raise ValueError('%s has host bits set' % self)
ValueError: 1.1.1.1/24 has host bits set
>>> ipaddress.IPv4Network("1.1.1.0/24")
IPv4Network('1.1.1.0/24')
```

Regardless, this is really for others benefit. I already created my newtype struct and tested it. I had to make it backward compatible on serde deserialization (in case my DB currently has invalid subnets, which it might?), but any new invalid subnets are now rejected at least.

**Comment by krisprice** [comment]
Hi Scott, yes it would still have to wait for v3, or perhaps it could+should be gated in a "strict" feature.

I don't know the software you're working on. How is IpNet being used and how did it cause a bug here? Is this taken from user input, was it bad user input you wanted IpNet to catch? From what you're saying there was some input with something like 1.1.1.1/24 and your software would've been fine if it had been input as 1.1.1.1/32 or 1.1.1.0/24. It would've been fine if it had used `trunc()`, so your software is happy assuming the intent of the input was to throw away the presumed host-bits and trust the prefix?

**Comment by ens-scmeeu** [comment]
That was probably a bad example, but it was just a simple one that makes the problem obvious. I'm asking that an `Ipv4Net` be an IPv4 net, and if it isn't an IPv4 net, return an error and disallow creation. This is in the same spirit of why we create email/phone types instead of holding things in a `String`, to ensure the type is valid before creating the type. If you want an IPv4 address and a mask, create a new type for it, but let's not allow bad combos of host bits and mask please.

As far as what is causing me issues, it is much more subtle. My users and I are experienced network engineers/architects who generally can do subnetting in our heads, but they assume my software will catch their mistakes, and I (and all other Rust devs) will assume a type of `Ipv4Net` will only hold an IPv4 subnet. As one real world example, someone entered `10.121.186.0/20`, which is not a valid subnet, as it is not on the proper bit boundary (they probably meant `10.121.176.0/20`). The first version of my software was written in Python, and the builtin `ipaddress.IPv4Network` catches this and throws an exception, as it should. A Rust type should not accept it either.

I apologize if this comes across as rude, that is not my intent, but you maintain a very important crate in the Rust ecosystem, and in Rust, we have high standards around safety (and not just memory safety, but using types to ensure proper operation as well). This type violates the ["principle of least astonishment"](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), so it should be redesigned IMO.

**Comment by ens-scmeeu** [comment]
This caused us another issue this morning. Ultimately, I think dividing this into two types in the next version is the right choice, but ultimately this won't fix us at this point and that is MY mistake. I've used it in both ways throughout my code (host + mask and network + mask), so at this point I would have to understand usage at each of the hundreds of places it was used to swap out the types correctly. I should have wrapped it as a second type day one, but by the time I realized the issue, it was too late. I will probably have to do so very carefully with the help of AI at some point.
